/**
 * Single place that maps a short name to a Font Awesome icon.
 * Icons are imported individually so the bundler tree-shakes the rest away.
 */
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faArrowRotateRight,
  faBan,
  faBarcode,
  faBars,
  faBell,
  faBolt,
  faCalendarDays,
  faCamera,
  faCheck,
  faFireExtinguisher,
  faHandshake,
  faHelmetSafety,
  faHospital,
  faIndustry,
  faKitMedical,
  faPhone,
  faShieldHalved,
  faStairs,
  faTowerBroadcast,
  faTruck,
  faWarehouse,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircleCheck,
  faCircleInfo,
  faDownload,
  faExpand,
  faGear,
  faGraduationCap,
  faIdCard,
  faImage,
  faKey,
  faLink,
  faMagnifyingGlass,
  faPaperPlane,
  faPenToSquare,
  faPlus,
  faPowerOff,
  faPrint,
  faQrcode,
  faRightFromBracket,
  faRotate,
  faStop,
  faTableColumns,
  faTrashCan,
  faTriangleExclamation,
  faUpRightFromSquare,
  faUser,
  faUserGear,
  faUsers,
  faXmark,
} from "@fortawesome/free-solid-svg-icons";

const ICONS = {
  "arrow-left": faArrowLeft,
  ban: faBan,
  barcode: faBarcode,
  bars: faBars,
  bolt: faBolt,
  calendar: faCalendarDays,
  camera: faCamera,
  check: faCheck,
  handshake: faHandshake,
  helmet: faHelmetSafety,
  hospital: faHospital,
  industry: faIndustry,
  "kit-medical": faKitMedical,
  "fire-extinguisher": faFireExtinguisher,
  phone: faPhone,
  "shield-check": faShieldHalved,
  stairs: faStairs,
  tower: faTowerBroadcast,
  truck: faTruck,
  warehouse: faWarehouse,
  "check-circle": faCircleCheck,
  "chevron-left": faChevronLeft,
  "chevron-right": faChevronRight,
  "chevron-up": faChevronUp,
  "chevron-down": faChevronDown,
  dashboard: faTableColumns,
  download: faDownload,
  edit: faPenToSquare,
  expand: faExpand,
  "external-link": faUpRightFromSquare,
  gear: faGear,
  image: faImage,
  info: faCircleInfo,
  key: faKey,
  link: faLink,
  logout: faRightFromBracket,
  "power-off": faPowerOff,
  plus: faPlus,
  print: faPrint,
  qrcode: faQrcode,
  refresh: faArrowRotateRight,
  rotate: faRotate,
  search: faMagnifyingGlass,
  stop: faStop,
  training: faGraduationCap,
  trash: faTrashCan,
  user: faUser,
  users: faUsers,
  "user-gear": faUserGear,
  badge: faIdCard,
  warning: faTriangleExclamation,
  "triangle-exclamation": faTriangleExclamation,
  bell: faBell,
  "paper-plane": faPaperPlane,
  xmark: faXmark,
};

export default function Icon({ name, className = "", ...rest }) {
  const icon = ICONS[name];
  if (!icon) return null;
  return (
    <FontAwesomeIcon icon={icon} className={`fa-ico ${className}`.trim()} {...rest} />
  );
}
